/* Área do círculo 
                 Ian S. Molina

//---------------------------------------------------------------------------------------

A fórmula para calcular a área de um  círculo é π*r² ,consideraremos π = 3,14.

r = ao raio do círculo 

//--------------------------------------------------------------------------------------*/

π = 3.14
r = prompt("raio")

A= (r**2)*π

alert("a área do círculo é :" +A)
